export const IpcChannel = {
  appGetInfo: 'app:get-info',
  configGet: 'config:get',
  configSetClaudeDir: 'config:set-claude-dir',
  configSetTheme: 'config:set-theme',
  configSetAutoSummarize: 'config:set-auto-summarize',
  configPickClaudeDir: 'config:pick-claude-dir',
  sessionsList: 'sessions:list',
  sessionsChanged: 'sessions:changed',
  recentDirsGet: 'recent-dirs:get',
  sessionPickDirectory: 'session:pick-directory',
  sessionCreate: 'session:create',
  sessionResume: 'session:resume',
  sessionRename: 'session:rename',
  sessionArchive: 'session:archive',
  archiveRestore: 'archive:restore',
  sessionDetail: 'session:detail',
  sessionSummarize: 'session:summarize',
  daySummarize: 'day:summarize',
  monthSummarize: 'month:summarize',
  summariesList: 'summaries:list',
  summariesGet: 'summaries:get',
  sessionExport: 'session:export',
  sessionReadText: 'session:read-text',
  uiGetState: 'ui:get-state',
  uiSaveState: 'ui:save-state',
  windowMinimize: 'window:minimize',
  windowToggleMaximize: 'window:toggle-maximize',
  windowIsMaximized: 'window:is-maximized',
  windowClose: 'window:close',
  windowSetBackgroundColor: 'window:set-background-color',
  windowMaximizedChanged: 'window:maximized-changed',
  sessionUsage: 'session:usage',
  searchQuery: 'search:query',
  sessionWrite: 'session:write',
  sessionResize: 'session:resize',
  sessionClose: 'session:close',
  sessionData: 'session:data',
  sessionExited: 'session:exited',
  sessionBound: 'session:bound',
  sessionError: 'session:error',
} as const;

export type IpcChannelName = (typeof IpcChannel)[keyof typeof IpcChannel];
