export const IpcChannel = {
  appGetInfo: 'app:get-info',
  configGet: 'config:get',
  configSetClaudeDir: 'config:set-claude-dir',
  configPickClaudeDir: 'config:pick-claude-dir',
  sessionsList: 'sessions:list',
  sessionPickDirectory: 'session:pick-directory',
  sessionCreate: 'session:create',
  sessionResume: 'session:resume',
  sessionRename: 'session:rename',
  sessionArchive: 'session:archive',
  archiveRestore: 'archive:restore',
  sessionDetail: 'session:detail',
  sessionExport: 'session:export',
  sessionReadText: 'session:read-text',
  uiGetState: 'ui:get-state',
  uiSaveState: 'ui:save-state',
  sessionUsage: 'session:usage',
  searchQuery: 'search:query',
  sessionWrite: 'session:write',
  sessionResize: 'session:resize',
  sessionClose: 'session:close',
  sessionData: 'session:data',
  sessionExited: 'session:exited',
  sessionBound: 'session:bound',
  sessionError: 'session:error',
} as const;

export type IpcChannelName = (typeof IpcChannel)[keyof typeof IpcChannel];
